services:
  minio:
    image: minio/minio:latest
    restart: unless-stopped
    container_name: minio
    command: minio server --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio.env:/etc/config.env
    environment:
      - MINIO_ROOT_USER=profile-admin
      - MINIO_ROOT_PASSWORD=profile-admin-password
      - MINIO_VOLUMES="/mnt/data"
      - MINIO_OPTS="--console-address :9001"
  minio-init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: /bin/sh -c "/usr/bin/mc alias set profile-s3 http://minio:9000 profile-admin profile-admin-password; /usr/bin/mc mb profile-s3/charitan-bucket; /usr/bin/mc policy set public profile-s3/charitan-bucket; exit 0;"
