services:
  postgres:
    image: 'postgres:alpine'
    environment:
      POSTGRES_DB: profile
      POSTGRES_USER: profile
      POSTGRES_PASSWORD: profile
    ports:
      - '5432'

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: secret
  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data

  garage:
    image: 'dxflrs/garage:3661a597fa40e6396049e4dd9fef50c14fa9e9d9'
    depends_on:
      - postgres
    ports:
      - '3900:3900'
      - '3901:3901'
      - '3902:3902'
    volumes:
      - './garage.toml:/etc/garage.toml'
      - 'garage-meta:/var/lib/garage/meta:rw'
      - 'garage-data:/var/lib/garage/data:rw'

volumes:
  garage-meta:
  garage-data:
  redis-insight:
