spring:
  application:
    name: profile
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 60000
      connection-timeout: 30000
      pool-name: MyHikariCP
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: auth-group
    producer:
      properties:
        max.block.ms: 120000
  data:
    redis:
      host: redis
      port: 6379
      password: default
      database: 0

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

logging:
  level:
    org.springframework.security: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
